service: yith

provider:
  name: aws
  runtime: nodejs4.3
  stage: dev
  region: eu-west-1
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "s3:ListBucket"
        - "s3:GetObject"
        - "s3:PutObject"
        - "logs:CreateLogGroup"
        - "logs:CreateLogStream"
        - "logs:PutLogEvents"
      Resource: "arn:aws:s3:::${self:service}*"

package:
  exclude:
    - ./src

functions:
  packageGet:
    handler: lib/package/get/index.handler
    events:
      - http:
          path: "registry/{id}"
          method: get
          request:
            template:
              application/json: '{ "id": "$input.params(''id'')", "registry": "https://registry.npmjs.org/", "bucket": "${self:service}-${opt:stage}", "region": "eu-west-1" }'
  packagePut:
    handler: lib/package/put/index.handler
    events:
      - http:
          path: "registry/{id}"
          method: put
          request:
            template:
              application/json: '{ "id": "$input.params(''id'')", "body": "$util.escapeJavaScript($input.json(''$''))", "registry": "https://registry.npmjs.org/", "bucket": "${self:service}-${opt:stage}", "region": "eu-west-1" }'
  userPut:
    handler: lib/user/put/index.handler
    events:
      - http:
          path: "registry/-/user/{id}"
          method: put
          statusCode: 201
          request:
            template:
              application/json: '{ "id": "$input.params(''id'')", "body": "$util.escapeJavaScript($input.json(''$''))", "registry": "https://registry.npmjs.org/" }'

resources:
  Resources:
    PackageStorage:
      Type: AWS::S3::Bucket
      Properties:
        AccessControl: PublicRead
        BucketName: ${self:service}-${opt:stage}
